<a href="https://colab.research.google.com/github/andres84/DataScienceProyect/blob/main/variacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#prueba de dataframe para calcular una variacion
import pandas as pd

matriz = {'año':['2019', '2020', '2021', '2022'],
          'Censo_2020':[1000, 2000, 500, 300]}
datos = pd.DataFrame(matriz)
datos

    año  Censo_2020
0  2019        1000
1  2020        2000
2  2021         500
3  2022         300

In [90]:
datos['dif'] = datos.Censo_2020.diff()
datos

    año  Censo_2020     dif   Var
0  2019        1000     NaN   NaN
1  2020        2000  1000.0  1.00
2  2021         500 -1500.0 -0.75
3  2022         300  -200.0 -0.40

In [ ]:
dife = datos.dif/datos.Censo_2020.shift(1)*100
datos['Var'] = dife/100

In [ ]:
datos

    año  Censo_2020     dif   Var
0  2019        1000     NaN   NaN
1  2020        2000  1000.0  1.00
2  2021         500 -1500.0 -0.75
3  2022         300  -200.0 -0.40